export const OPERATIONS_DEFAULTS: Record<string, string> = {
  agreementName: '',
  agreementAddress: '',
  agreementContact: '',
  enrollmentPlanType: '',
  finalPaymentConditions: '',
  currentAgreedPaymentCondition: '',
  currentAgreedPaymentConditions: '',
  preAuthoritySign: '',
  priAuthoritySignatureImage: '',
  signatureBoxLabel: 'Sign Here',
  issueDate: new Date().toISOString().slice(0, 10),
  dueDate: '',
  documentNumber: '',
  clientLegalName: '',
  clientAddress: '',
  contactName: '',
  contactEmail: '',
  serviceDescription: 'Offshore accounting staffing services',
  billingPeriod: '',
  amount: '',
  taxOrFees: 'As applicable',
  paymentTerms: 'Net 14 days',
  notes: '',
  candidateName: '',
  candidateEmail: '',
  jobTitle: '',
  department: '',
  workLocation: 'Ahmedabad, India / Remote',
  startDate: '',
  compensation: '',
  reportingManager: '',
  employmentType: 'Full-time',
  probationPeriod: '3 months',
  confirmationDate: '',
  effectiveDate: new Date().toISOString().slice(0, 10),
  disclosingSignatoryName: 'NetBounce Placement LLC',
  disclosingSignatoryTitle: 'Authorised Signatory',
  disclosingSignatoryDate: new Date().toISOString().slice(0, 10),
  receivingSignatoryName: '',
  receivingSignatoryTitle: '',
  receivingSignatoryDate: '',
  invoiceNumber: '',
  invoiceDate: new Date().toISOString().slice(0, 10),
  salespersonEmail: '',
  candidatePhone: '',
  packName: '',
  packAmount: '',
  comments: '',
  candidate_name: '',
  candidate_email: '',
  candidate_phone: '',
  invoice_no: '',
  pack_name: '',
  deliverables: 'As per the services mentioned in pricing document',
  pack_amount: '',
  upfront_details: '',
  remaining_details: '',
  terms_comment: '8% of your gross annual salary package in 4 installments calculated as per offer letter',
  advance_amount: '',
  pending_amount: '',
  advance_received: '',
  pending_balance: '',
  due_date: '',
  total_paid: '',
  final_pending: '',
  discountPercentage: '',
  discountAmount: '',
  enrollmentFee: '',
  enrollmentPaidDate: '',
  firstInstallmentAmount: '',
  firstInstallmentPaidDate: '',
  secondInstallmentAmount: '',
  secondInstallmentDueDate: '',
  totalAmount: '',
  totalAmountPaid: '',
  totalAmountDue: '',
  employeeName: '',
  employeeCode: '',
  designation: '',
  letterDate: new Date().toISOString().slice(0, 10),
  work_location: '',
  employee_state: '',
  dateOfJoining: '',
  monthlyGrossSalary: '',
  employeeTitle: '',
  addressLine1: '',
  addressLine2: '',
  addressLine3: '',
  location: '',
  annualCtc: '',
  monthlyCtc: '',
  employee_name: '',
  letterdate: new Date().toISOString().slice(0, 10),
  doj: '',
  MONTHLY_GROSS_FULL: '',
  employeetitle: '',
  employeename: '',
  'add line 1': '',
  'add line 2': '',
  'add line 3': '',
  CTC_TOTAL_FULL: '',
  PLI_FULL: '',
  Employee_Name: '',
  Employee_Code: '',
  Designation: '',
  date: new Date().toISOString().slice(0, 10),
  'DD-MM-YYYY': '',
}

export const AGREEMENT_SECTIONS = [
  { id: 'agreement-admin', label: 'Admin Controlled Agreement Fields', fields: ['enrollmentPlanType', 'finalPaymentConditions', 'currentAgreedPaymentConditions', 'priAuthoritySignatureImage', 'signatureBoxLabel'] },
]

export const PRE_INVOICE_SECTIONS = [
  { id: 'invoice', label: 'Invoice Details', fields: ['invoice_no', 'date'] },
  { id: 'candidate', label: 'Candidate Details', fields: ['candidate_name', 'candidate_email', 'candidate_phone'] },
  { id: 'pack', label: 'Service Breakdown', fields: ['pack_name', 'deliverables', 'pack_amount', 'upfront_details', 'remaining_details', 'terms_comment'] },
  { id: 'payment', label: 'Payment Summary', fields: ['advance_amount', 'pending_amount'] },
]

export const SLOT_INVOICE_RECEIPT_SECTIONS = [
  { id: 'invoice', label: 'Invoice Details', fields: ['invoice_no', 'date', 'dueDate'] },
  { id: 'candidate', label: 'Candidate Details', fields: ['candidate_name', 'candidate_email', 'candidate_phone'] },
  { id: 'pack', label: 'Service Breakdown', fields: ['pack_name', 'deliverables', 'pack_amount', 'upfront_details', 'remaining_details', 'terms_comment'] },
  { id: 'payment', label: 'Receipt Summary', fields: ['advance_received', 'pending_balance'] },
]

export const FINAL_INVOICE_RECEIPT_SECTIONS = [
  { id: 'invoice', label: 'Invoice Details', fields: ['invoice_no', 'date'] },
  { id: 'candidate', label: 'Candidate Details', fields: ['candidate_name', 'candidate_email', 'candidate_phone'] },
  { id: 'pack', label: 'Service Breakdown', fields: ['pack_name', 'deliverables', 'pack_amount', 'upfront_details', 'remaining_details', 'terms_comment'] },
  { id: 'payment', label: 'Final Payment Summary', fields: ['total_paid', 'final_pending'] },
]

export const HR_LETTER_SECTIONS = [
  { id: 'employee', label: 'Employee Details', fields: ['letterDate', 'employeeTitle', 'employeeName', 'employeeCode', 'candidateEmail', 'designation', 'department'] },
  { id: 'address', label: 'Address / Location', fields: ['addressLine1', 'addressLine2', 'addressLine3', 'work_location', 'employee_state', 'location'] },
  { id: 'employment', label: 'Employment Terms', fields: ['dateOfJoining', 'monthlyGrossSalary', 'annualCtc', 'monthlyCtc'] },
]

export const APPOINTMENT_LETTER_SECTIONS = [
  { id: 'appointment-fields', label: 'Appointment Letter Fields', fields: ['employee_name', 'work_location', 'employee_state', 'letterdate', 'designation', 'doj', 'department', 'location', 'MONTHLY_GROSS_FULL'] },
]

export const OFFER_LETTER_SECTIONS = [
  { id: 'offer-fields', label: 'NB Offer Letter Fields', fields: ['letterdate', 'employeetitle', 'employeename', 'add line 1', 'add line 2', 'add line 3', 'designation', 'department', 'doj', 'location', 'CTC_TOTAL_FULL', 'PLI_FULL'] },
]

export const CONFIRMATION_LETTER_SECTIONS = [
  { id: 'confirmation-fields', label: 'Confirmation Letter Fields', fields: ['date', 'Employee_Name', 'Employee_Code', 'Designation', 'DD-MM-YYYY'] },
]

export const OPERATIONS_FIELD_CONFIG: Record<string, { label: string; placeholder?: string; type?: string; multiline?: boolean }> = {
  agreementName: { label: 'Candidate name', placeholder: 'Filled by candidate' },
  agreementAddress: { label: 'Candidate address', placeholder: 'Filled by candidate', multiline: true },
  agreementContact: { label: 'Candidate contact number', placeholder: 'Filled by candidate' },
  enrollmentPlanType: { label: 'Enrollment plan type', placeholder: 'e.g. Standard / Premium' },
  finalPaymentConditions: { label: 'Final payment conditions', multiline: true },
  currentAgreedPaymentCondition: { label: 'Current agreed payment condition', multiline: true },
  currentAgreedPaymentConditions: { label: 'Current agreed payment conditions', multiline: true },
  preAuthoritySign: { label: 'PRI authority signature reference' },
  priAuthoritySignatureImage: { label: 'PRI authority signature image', type: 'image' },
  signatureBoxLabel: { label: 'Candidate signature box label', placeholder: 'Sign Here' },
  issueDate: { label: 'Issue date', type: 'date' },
  dueDate: { label: 'Due Date', type: 'date' },
  documentNumber: { label: 'Document number', placeholder: 'e.g. PF-2026-001' },
  billingPeriod: { label: 'Billing period', placeholder: 'e.g. May 2026' },
  clientLegalName: { label: 'Legal name', placeholder: 'Client company legal name' },
  clientAddress: { label: 'Client address', multiline: true },
  contactName: { label: 'Contact name' },
  contactEmail: { label: 'Contact email', type: 'email' },
  serviceDescription: { label: 'Service description', multiline: true },
  amount: { label: 'Amount', placeholder: 'e.g. USD 2,500' },
  taxOrFees: { label: 'Taxes / fees', placeholder: 'e.g. Included / As applicable' },
  paymentTerms: { label: 'Payment terms', placeholder: 'e.g. Net 14 days' },
  notes: { label: 'Notes', multiline: true },
  candidateName: { label: 'Candidate / employee name' },
  candidateEmail: { label: 'Candidate / employee email', type: 'email' },
  jobTitle: { label: 'Role / designation' },
  department: { label: 'Department' },
  workLocation: { label: 'Work location' },
  startDate: { label: 'Start date', type: 'date' },
  compensation: { label: 'Compensation', placeholder: 'e.g. INR 8,00,000 per annum' },
  reportingManager: { label: 'Reporting manager' },
  employmentType: { label: 'Employment type' },
  probationPeriod: { label: 'Probation period' },
  confirmationDate: { label: 'Confirmation date', type: 'date' },
  effectiveDate: { label: 'Effective date', type: 'date' },
  disclosingSignatoryName: { label: 'NPB signatory name' },
  disclosingSignatoryTitle: { label: 'NPB signatory title' },
  disclosingSignatoryDate: { label: 'NPB signatory date', type: 'date' },
  receivingSignatoryName: { label: 'Recipient signatory name' },
  receivingSignatoryTitle: { label: 'Recipient signatory title' },
  receivingSignatoryDate: { label: 'Recipient signatory date', type: 'date' },
  invoiceNumber: { label: 'Invoice number', placeholder: 'e.g. INV-2026-001' },
  invoiceDate: { label: 'Invoice date', type: 'date' },
  salespersonEmail: { label: 'Salesperson email', type: 'email' },
  candidatePhone: { label: 'Candidate phone number' },
  packName: { label: 'Pack name' },
  packAmount: { label: 'Pack amount', placeholder: 'e.g. 50000' },
  comments: { label: 'Comments', multiline: true },
  discountPercentage: { label: 'Discount percentage', placeholder: '10' },
  discountAmount: { label: 'Discount amount ($)', placeholder: '5000' },
  enrollmentFee: { label: 'Enrollment fee / upfront amount' },
  enrollmentPaidDate: { label: 'Enrollment paid date', type: 'date' },
  firstInstallmentAmount: { label: 'First installment amount' },
  firstInstallmentPaidDate: { label: 'First installment paid date', type: 'date' },
  secondInstallmentAmount: { label: 'Second installment amount' },
  secondInstallmentDueDate: { label: 'Second installment due date', type: 'date' },
  totalAmount: { label: 'Total amount' },
  totalAmountPaid: { label: 'Total amount paid' },
  totalAmountDue: { label: 'Total amount due' },
  candidate_name: { label: 'Candidate name', placeholder: 'Xyz Sharma' },
  candidate_email: { label: 'Candidate email', type: 'email', placeholder: 'xyz.sharma@needjob.com' },
  candidate_phone: { label: 'Candidate no.', placeholder: '+916699696969' },
  invoice_no: { label: 'Invoice no.', placeholder: 'INV/26/001' },
  pack_name: { label: 'Pack', placeholder: 'Starter Plan:' },
  deliverables: { label: 'Deliverables comment', placeholder: 'As per the services mentioned in pricing document', multiline: true },
  pack_amount: { label: 'Pack amount', placeholder: '$5000.00' },
  upfront_details: { label: 'Upfront comment', placeholder: '$3000 upfront,' },
  remaining_details: { label: 'Remaining comment', placeholder: '$2500 payable when offer letter is received,' },
  terms_comment: { label: 'General comment', placeholder: '8% of your gross annual salary package...', multiline: true },
  advance_amount: { label: 'Advance paid', placeholder: '$500.00' },
  pending_amount: { label: 'Total pending', placeholder: '$4500.00' },
  advance_received: { label: 'Advance Received', placeholder: '$1500.00' },
  pending_balance: { label: 'Total Pending', placeholder: '$1500.00' },
  due_date: { label: 'Due Date', type: 'date' },
  total_paid: { label: 'Advance Received', placeholder: '$3000.00' },
  final_pending: { label: 'Total Pending', placeholder: '$0.00' },
  employeeName: { label: 'Employee name' },
  employeeCode: { label: 'Employee code' },
  designation: { label: 'Designation' },
  letterDate: { label: 'Letter date', type: 'date' },
  work_location: { label: 'Work location' },
  employee_state: { label: 'Employee state' },
  dateOfJoining: { label: 'Date of joining', type: 'date' },
  monthlyGrossSalary: { label: 'Monthly gross salary' },
  employeeTitle: { label: 'Employee title' },
  addressLine1: { label: 'Address line 1' },
  addressLine2: { label: 'Address line 2' },
  addressLine3: { label: 'Address line 3' },
  location: { label: 'Location' },
  annualCtc: { label: 'Annual CTC' },
  monthlyCtc: { label: 'Monthly CTC' },
  employee_name: { label: 'employee_name' },
  letterdate: { label: 'letterdate', type: 'date' },
  doj: { label: 'doj', type: 'date' },
  MONTHLY_GROSS_FULL: { label: '₹{MONTHLY_GROSS_FULL}' },
  employeetitle: { label: 'employeetitle' },
  employeename: { label: 'employeename' },
  'add line 1': { label: 'add line 1' },
  'add line 2': { label: 'add line 2' },
  'add line 3': { label: 'add line 3' },
  CTC_TOTAL_FULL: { label: 'CTC_TOTAL_FULL' },
  PLI_FULL: { label: 'PLI_FULL' },
  Employee_Name: { label: 'Employee_Name' },
  Employee_Code: { label: 'Employee_Code' },
  Designation: { label: 'Designation' },
  date: { label: 'date', type: 'date' },
  'DD-MM-YYYY': { label: 'DD-MM-YYYY', type: 'date' },
}
